CREATE USER EVENT_STORE IDENTIFIED BY EVENT_STORE DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;
GRANT CONNECT TO EVENT_STORE;
GRANT RESOURCE TO EVENT_STORE;
ALTER USER EVENT_STORE DEFAULT ROLE CONNECT,RESOURCE;
GRANT CREATE SESSION TO EVENT_STORE;

CREATE USER EVENT_STORE_APP IDENTIFIED BY EVENT_STORE_APP;
GRANT CONNECT TO EVENT_STORE_APP;
